services:
  aoc2024-dev:
    container_name: aoc2024-dev
    build:
      context: .
      tags:
        - "aoc2024-dev:latest"
      labels:
        - "local=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace:cached
      - ${SSH_DIR?}:/root/.ssh